main.exe: utile.o data.o evento.o bst_evento.o conferenza.o main.o
gcc -I./headers_file utile.o data.o evento.o bst_evento.o conferenza.o main.o -o main.exe

utile.o: utile.c utile.h
gcc -c -I./headers_file utile.c

data.o: data.c data.h utile.h
gcc -c -I./headers_file data.c

evento.o: evento.c evento.h utile.h data.h
gcc -c -I./headers_file evento.c

bst_evento.o: bst_evento.c evento.h 
gcc -c -I./headers_file bst_evento.c

conferenza.o: conferenza.c conferenza.h utile.h data.h
gcc -c -I./headers_file conferenza.c

main.o: main.c utile.h conferenza.h
gcc -c -I./headers_file main.c
